apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    run: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector: 
    component: {{ .Release.Name }}
  ports:
  - name: grpcs
    port: 7050
    protocol: TCP
    targetPort: 7050
  - name: admin
    port: 7080
    protocol: TCP
    targetPort: 7080