# Different paths that contain the crypto material
{{ $genesisBlockPath := printf "blocks/genesis.block" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-blocks
type: Opaque
data:
  genesis_block: {{ .Files.Get $genesisBlockPath | b64enc }}
