# Variable assignment to make the following processes easier...
{{ $organizationName := print .Values.organization.name}}

# Different paths that contain the crypto material
{{ $peerTlsCaCertPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/tls/ca.crt" $organizationName $organizationName }}
{{ $peerTlsServerCertPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/tls/server.crt" $organizationName $organizationName }}
{{ $peerTlsServerKeyPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/tls/server.key" $organizationName $organizationName }}

{{ $adminConfigYamlPath := printf "crypto/%s.example.com/users/Admin@%s.example.com/msp/config.yaml" $organizationName $organizationName }}
{{ $adminCaCertPath := printf "crypto/%s.example.com/users/Admin@%s.example.com/msp/cacerts/ca.%s.example.com-cert.pem" $organizationName $organizationName $organizationName }}
{{ $adminPrivateKeyPath := printf "crypto/%s.example.com/users/Admin@%s.example.com/msp/keystore/priv_sk" $organizationName $organizationName }}
{{ $adminSigncertsPath := printf "crypto/%s.example.com/users/Admin@%s.example.com/msp/signcerts/Admin@%s.example.com-cert.pem" $organizationName $organizationName $organizationName }}

{{ $ordererTlsCaCertPath := printf "crypto/orderer/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem" }}


apiVersion: v1
kind: Secret
metadata:
  name: cli-peer-{{ .Values.organization.name }}-crypto-material
type: Opaque
data:
  peer_tls_ca_cert: {{ .Files.Get $peerTlsCaCertPath | b64enc }}
  peer_tls_server_cert: {{ .Files.Get $peerTlsServerCertPath | b64enc }}
  peer_tls_server_key: {{ .Files.Get $peerTlsServerKeyPath | b64enc }}

  peer_admin_msp_config: {{ .Files.Get $adminConfigYamlPath | b64enc }}
  peer_admin_ca_cert: {{ .Files.Get $adminCaCertPath | b64enc }}
  peer_admin_private_key: {{ .Files.Get $adminPrivateKeyPath | b64enc }}
  peer_admin_signcert: {{ .Files.Get $adminSigncertsPath | b64enc }}

  orderer_tls_ca_cert: {{ .Files.Get $ordererTlsCaCertPath | b64enc }}