# Different paths that contain the crypto material
{{ $channelBlockPath := printf "blocks/test-channel.tx" }}

apiVersion: v1
kind: Secret
metadata:
  name: cli-peer-{{ .Values.organization.name }}-channel-block
type: Opaque
data:
  channel_block: {{ .Files.Get $channelBlockPath | b64enc }}
