# Variable assignment to make the following processes easier...
{{ $organizationName := print .Values.organization.name}}

# Different paths that contain the crypto material
{{ $configYamlPath := printf "crypto/%s.example.com/msp/config.yaml" $organizationName }}
{{ $signcertsPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/msp/signcerts/peer0.%s.example.com-cert.pem" $organizationName $organizationName $organizationName }}
{{ $privateKeyPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/msp/keystore/priv_sk" $organizationName $organizationName }}
{{ $caCertPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/msp/cacerts/ca.%s.example.com-cert.pem" $organizationName $organizationName $organizationName }}
{{ $tlsCaCertPath := printf "crypto/%s.example.com/peers/peer0.%s.example.com/tls/ca.crt" $organizationName $organizationName }}
{{ $tlsServerCert := printf "crypto/%s.example.com/peers/peer0.%s.example.com/tls/server.crt" $organizationName $organizationName }}
{{ $tlsServerKey := printf "crypto/%s.example.com/peers/peer0.%s.example.com/tls/server.key" $organizationName $organizationName }}

apiVersion: v1
kind: Secret
metadata:
  name: peer-{{ .Values.organization.name }}-crypto-material
type: Opaque
data:
  peer_msp_config: {{ .Files.Get $configYamlPath | b64enc }}
  peer_signcerts: {{ .Files.Get $signcertsPath | b64enc }}
  peer_private_key: {{ .Files.Get $privateKeyPath | b64enc }}
  peer_ca_cert: {{ .Files.Get $caCertPath | b64enc }}
  peer_tls_ca_cert: {{ .Files.Get $tlsCaCertPath | b64enc }}
  peer_tls_server_cert: {{ .Files.Get $tlsServerCert | b64enc }}
  peer_tls_server_key: {{ .Files.Get $tlsServerKey | b64enc }}
