apiVersion: v1
kind: Service
metadata:
  name: peer-{{ .Values.organization.name }}
  labels:
    run: peer-{{ .Values.organization.name }}
spec:
  type: ClusterIP
  selector:
    component: peer-{{ .Values.organization.name }}
  ports:
  - name: grpcs
    port: 7051
    protocol: TCP
    targetPort: 7051