#!/bin/bash

# Helper function to print usage
print_usage() {
  echo "Network tool"
  echo "Basic commands:"
  echo "  start : Starts a HLF network on a namespace "
  echo "  stop : Stops a running HLF network on a namespace"
}

setup() {
  cd fabric-network
  ./scripts/setup.sh
}

start() {
  cd fabric-network
  ./scripts/start.sh
}

stop() {
  cd fabric-network
  ./scripts/stop.sh
}

if [[ $# -eq 0 ]]; then
  print_usage
  exit 0
fi

COMMAND=$1
if [ "$COMMAND" == "start" ]; then
  setup
  start
elif [ "$COMMAND" == "stop" ]; then
  stop
else
  echo "Unrecognized command $COMMAND"
  print_usage
  exit 1
fi